---
satellite_firewall_ports:
  - 443/tcp
  - 80/tcp
  - 5647/tcp
  - 8000/tcp
  - 8140/tcp
  - 8443/tcp
  - 9090/tcp
  - 5000/tcp
  - 53/tcp
  - 53/udp
  - 67/udp
  - 69/udp
  - 5646/tcp
  - 7/udp
  - 7/tcp
  - 68/udp
