---
# Updates Satellite Servers or Satellite Capsule Servers to latest micro version.
# 
# PARAMETERS
# 
# @param satellite_scenario     `satellite` or `capsule`
# @param satellite_repositories Exclusive list of repositories to be enabled pre-update
#
# @see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.2/html-single/installation_guide/#updating_satellite_server_to_next_minor_version
# @see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.2/html-single/installation_guide/#updating_capsule_server_to_next_minor_version
# @see https://access.redhat.com/solutions/3222091

- name: Satellite | Update | Disable All Repositories
  command: "subscription-manager repos --disable='*'"
  become: True

- name: Satellite | Update | Enable Required Repositories
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items: "{{ satellite_repositories }}"
  become: True

# need to ensure this is installed before katello is shutdown
- name: Satellite | Update | Install yum-utils
  package:
    name: yum-utils
    state: present

# can't use `yum` or `package` modules because no way to pass `--downloadonly` flag
- name: Satellite | Update | Download updated packages
  command: yum update --downloadonly
  become: True

- name: Satellite | Update | Stop Katello
  command: katello-service stop
  become: True

# can't use `yum` or `package` modules because no way to pass `--cachonly` flag
# NOTE: this differs from update instructions due to https://access.redhat.com/solutions/3222091
- name: Satellite | Update | Update all packages
  command: yum update --cache --disableplugin=enabled_repos_upload --disableplugin=package_upload --disableplugin=subscription-manager
  become: True

- name: Satellite | Update | Stop Katello
  command: katello-service stop
  become: True

- name: Satellite | Update | Run satellite-installer upgrader
  command: "satellite-installer --scenario {{ satellite_scenario }} --upgrade"
  become: True
  register: satellite_server_upgrade

- name: Satellite | Update | Reboot if Required
  include_tasks: host-reboot.yml
  vars:
    host_reboot_only_if_needed: True

- name: Satellite | Update | Restart goferd
  service:
    name: goferd
    state: restarted
  become: True
  when: host_reboot.changed
