---
# Updates Satellite Capsule
# 
# @see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html-single/upgrading_and_updating_red_hat_satellite/#updating_capsule_server_to_next_minor_version

- name: Satellite | Update | Satellite Capsule | Include tasks for enabling repositories
  include_tasks: tasks/repositories.yml
  vars:
    repositories:
      - rhel-7-server-rpms
      - rhel-7-server-satellite-capsule-6.3-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-satellite-tools-6.3-rpms

- name: Satellite | Update | Satellite Capsule | Stop Katello
  command: katello-service stop

- name: Satellite | Update | Satellite Capsule | Update all packages
  package:
    name: '*'
    state: latest

- name: Satellite | Update | Satellite Capsule | Upgrade
  command: satellite-installer --scenario capsule --upgrade

- name: Satellite | Update | Satellite Capsule | Include tasks for host reboot
  include_tasks: host-reboot.yml
  vars:
    host_reboot_only_if_needed: True

- name: Satellite | Update | Satellite Capsule | Restart goferd
  service:
    name: goferd
    state: restarted
  become: True
  when: host_reboot.changed
