---
# Updates Satellite Servers
# 
# @see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html-single/upgrading_and_updating_red_hat_satellite/#updating_satellite_server_to_next_minor_version

- name: Satellite | Update | Satellite Servers | Include tasks for enabling repositories
  include_tasks: tasks/repositories.yml
  vars:
    repositories:
      - rhel-7-server-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-satellite-6.3-rpms

- name: Satellite | Update | Satellite Servers | Update all packages
  package:
    name: '*'
    state: latest

- name: Satellite | Update | Satellite Servers | Upgrade
  command: satellite-installer --scenario satellite --upgrade

- name: Satellite | Update | Satellite Servers | Include tasks for host reboot
  include_tasks: host-reboot.yml
  vars:
    host_reboot_only_if_needed: True
