---
# Updates Satellite Servers and Satellite Capsules to the next minor version.
- name: Satellite | Update | Satellite Servers
  hosts: satellite-servers
  tasks:
    - include_tasks: tasks/satellite-update.yml
      vars:
        satellite_scenario: satellite
        satellite_repositories:
          - rhel-7-server-rpms
          - rhel-7-server-satellite-6.2-rpms
          - rhel-server-rhscl-7-rpms

- name: Satellite | Update | Satellite Capsule Servers
  hosts: satellite-capsule-servers
  tasks:
    - include_tasks: tasks/satellite-update.yml
      vars:
        satellite_scenario: capsule
        satellite_repositories:
          - rhel-7-server-rpms
          - rhel-7-server-satellite-capsule-6.2-rpms
          - rhel-server-rhscl-7-rpms
          - rhel-7-server-satellite-tools-6.2-rpms
